[package]
name = "duel"
version = "0.2.0"
cairo-version = ">=2.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
cubit = { git = "https://github.com/influenceth/cubit" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.2.1"}

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
account_address = "0x06f62894bfd81d2e396ce266b2ad0f21e0668d604e5bb1077337b6d570a54aea"
private_key = "0x07230b49615d175307d580c33d6fda61fc7b9aec91df0f5c1a5ebe3b8cbfee02"

world_address="0x26065106fa319c3981618e7567480a50132f23932226a51c219ffb8e47daa84"
